"""empty message

Revision ID: f336fad91884
Revises: ffe511aa2b79
Create Date: 2025-01-15 20:21:48.326034

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f336fad91884"
down_revision: Union[str, None] = "ffe511aa2b79"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "meeting_tasks", "meeting_id", existing_type=sa.INTEGER(), nullable=False
    )
    op.alter_column(
        "meeting_tasks", "task_id", existing_type=sa.INTEGER(), nullable=False
    )
    op.drop_index("ix_meeting_task_meeting_id", table_name="meeting_tasks")
    op.drop_index("ix_meeting_task_task_id", table_name="meeting_tasks")
    op.drop_constraint(
        "meeting_tasks_meeting_id_fkey", "meeting_tasks", type_="foreignkey"
    )
    op.drop_constraint(
        "meeting_tasks_task_id_fkey", "meeting_tasks", type_="foreignkey"
    )
    op.create_foreign_key(
        None, "meeting_tasks", "tasks", ["task_id"], ["id"], ondelete="CASCADE"
    )
    op.create_foreign_key(
        None, "meeting_tasks", "meetings", ["meeting_id"], ["id"], ondelete="CASCADE"
    )
    op.drop_column("meeting_tasks", "id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "meeting_tasks",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
    )
    op.drop_constraint(None, "meeting_tasks", type_="foreignkey")
    op.drop_constraint(None, "meeting_tasks", type_="foreignkey")
    op.create_foreign_key(
        "meeting_tasks_task_id_fkey", "meeting_tasks", "tasks", ["task_id"], ["id"]
    )
    op.create_foreign_key(
        "meeting_tasks_meeting_id_fkey",
        "meeting_tasks",
        "meetings",
        ["meeting_id"],
        ["id"],
    )
    op.create_index(
        "ix_meeting_task_task_id", "meeting_tasks", ["task_id"], unique=False
    )
    op.create_index(
        "ix_meeting_task_meeting_id", "meeting_tasks", ["meeting_id"], unique=False
    )
    op.alter_column(
        "meeting_tasks", "task_id", existing_type=sa.INTEGER(), nullable=True
    )
    op.alter_column(
        "meeting_tasks", "meeting_id", existing_type=sa.INTEGER(), nullable=True
    )
    # ### end Alembic commands ###
